export const MAIN_ERROR = 'MAIN_ERROR'
export const MAIN_GET_USER_LIST = 'MAIN_GET_USER_LIST';
export const MAIN_GET_POST_LIST = 'MAIN_GET_POST_LIST';
export const MAIN_CREATE_USER = 'MAIN_CREATE_USER';
export const MAIN_EDITING_USER = 'MAIN_EDITING_USER'
